// Copyright (c) 2026 Anything Left Behind?. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * 
 */

namespace GuestGameplayTags
{
	//UI 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_Frontend); //최하단 타이틀, 메인 메뉴, 설정
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_GameHUD); //2 시간대, 수거 목표, 상호작용 프롬프트
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_GameMenu); //3 수거 일지, 인벤토리, NPC 대화
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_Modal); //최상단 확인창, 아이템 발견 연출
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_BarDialogue); //바 모드 전체화면 대화 (VA-11 HALL-A 스타일)
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WidgetStack_Narration); //퀘스트 완료 등 스토리 분기 전환 나레이션 (전체화면)

	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_PressAnyKey);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_PauseMenu);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_GameHUD);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_Options);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_MainMenu);

	// 인벤토리 위젯 식별 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_Inventory);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_Digicam);
	
	// 세이브/ 로드 위젯 식별 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_SaveBoard);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_LoadBoard);
	
	// NPC 대화 위젯 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_NPCDialogue);

	// 바 모드 대화 위젯 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_BarDialogue);

	// 나레이션 위젯 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Widget_Narration);

	//아이템 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Weapon);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Consumable);
	
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Era_1995);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Era_2026);
	
	//테스트 인풋
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Test);
	
	//인풋
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Interact);

	//Ability
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Interact);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Flash);

	//인풋
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Flash);

	//State
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Dead);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Blinded);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Alert_Calm);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Alert_Suspicious);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Alert_Alerted);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Alert_Chasing);

	//Enemy 타입 식별 태그
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Enemy_Type_Reality);
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Enemy_Type_AfterImage);

	//GE SetByCaller 데이터
	GUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_PurifyAmount);
}

